# Generated by Django 2.2.4 on 2020-11-18 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripBuddyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.TextField(default='No Description Was Given')),
                ('tripStart', models.DateField()),
                ('tripEnd', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='tripBuddyApp.User')),
                ('participants', models.ManyToManyField(related_name='participate', to='tripBuddyApp.User')),
            ],
        ),
    ]
